language: python
python:
- 3.6
- "nightly"

matrix:
  allow_failures:
    - python: "nightly"

sudo: false

env:
  global:
    - MASTER_BRANCH=master
    - GH_USERNAME=lheagy
    - TWINE_USERNAME=lheagy
    - secure: "pf4vT9kh7JbPE1K94F8Mvj++J4a3ckA6EcrC3DiTi2/NVdHyQwGljDm8a31Nm5Nii+ZduAhID7o5ZLJbNYPTMTzuBL4lWbsFfoaMxCN0ckFPAMF305d3ldyqT0WzO1GRIqw0ERYMm+h0gGqNnmTQ1bCtGU8VO9jEQ58o80cydlFOqgHt46Hk3k4H7G3p1XtJFQ4rG0ekryWqPSuZNWfGwDJvD5Na+1bJaAgDwaNyVRNyhbk3toOG7VoD85n1NttQ+eJYAspwEfSIKKSvrjqWd5uwBwupnOhkZFlniXw9jl8vClJG4UTZixIHPpMiqjjMZoUVrzjEoTzwZ/Zx/pAWDSCkAWfPem7snJ0Ob8qkIKozIiIQ2gNcx/QSoIf+aZnZ1cmcmS4KAnx4HxM5kI40JRuKRmL60ybhzhbG0o+0fkunSvqJoHp5Lzmax+QqQtmdjDOZNi5aepo+LgTomhKpRb0xdcVH1sh/eRwca2DLL/dOcodCHeQThnNXa42hjWT382Q0ZDNAKE26Q8m3N13lI9MM1ln3rNdyBLlYEap/wmsYXD2bXWuhjvGvFiFjIKiWF0oGD3U1zx+0UMqTiuAfdh4P0TsRIBsKLqcMIrEOOzppfXHD+3Kx94Cn4kYjTT+uAHokm4Du9X+GC4qYostxt3UhAAHLENT5fVfwMvgVHQY="

install:
  - pip install -r requirements-dev.txt
  - make install

script:
  - make test
  - make check
  - make lint

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    script: ci/deploy-pypi.sh
    on:
        tags: true
        branch: master
