language: python
python:
- 3.6
- 3.7

sudo: false

env:
  global:
    - MASTER_BRANCH=master
    - PYPI_PY=3.6  # deploy to pypi from python 3.6

install:
  - pip install -r requirements-dev.txt
  - make install

script:
  - make test
  - make check
  - make lint

after_success:

  - bash <(curl -s https://codecov.io/bash)

  # early exit if not on a deplotment branch
  - if ! [ "$TRAVIS_BRANCH" = "$MASTER_BRANCH" -o "$TRAVIS_TAG" = "true" ]; then
      echo "Not deploying (because this is not a deployment branch)" ;
      exit 0 ;
    fi
  - if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then
      echo "Not deploying (because this is a pull request)" ;
      exit 0 ;
    fi

  # unpack credentials
  - openssl aes-256-cbc -K $encrypted_9f42beb9a57a_key -iv $encrypted_9f42beb9a57a_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
  - tar -xzf credentials.tar.gz

  # deploy to pypi on tags
  - mv credentials/.pypirc ~/.pypirc ;
  - make deploy;


notifications:
  slack: simpeg:1KZq5giMtlJJ58TijIPgqf7n
